apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: hello-api
    namespace: develop
  spec:
    ingressClassName: nginx
    tls:
      - hosts: [hello.local]
        secretName: hello-api-tls
    rules:
    - host: hello.local
      http:
        paths:
        - backend:
            service:
              name: hello-api
              port:
                number: 80
          path: /
          pathType: Prefix
kind: List
metadata: {}
