apiVersion: v1
kind: Secret
metadata:
  name: hello-app-tls
  namespace: hello
type: kubernetes.io/tls
data:
  # base64-encoded contents of your files:
  tls.crt: REPLACE_WITH_BASE64_CERT
  tls.key: REPLACE_WITH_BASE64_KEY
